Repository NachoPasser/OnDrive, pull requests merged in 2022-07, with the labels that each got.

#11 Agregar Validaciones al Modelo Car + Archivo Validator.js
  api/src/Models/Car.js
  api/src/Models/Validators/validators.js
Labels: enhancement

#19 Agregar campos Color y License Plate
  api/src/Models/Car.js
Labels: enhancement

#21 Correccion de ruta /models
  api/src/db.js
Labels: fix

#33 Conecte el filtro de fechas con el store
  client/src/SearchBar/filterByDate.jsx
  client/src/redux/actions/getTripsByDate.js
  client/src/redux/reducer/reducer.js
Labels: fix

#37 Actualizo filtros y ordenes
  api/src/controllers/usersJson.js
  client/package.json
  client/src/Home/home.js
  client/src/SearchBar/filterByDestination.jsx
  client/src/SearchBar/filterByOrigin.jsx
  client/src/SearchBar/sortAlphabetically.jsx
  client/src/SearchBar/sortByRating.jsx
  client/src/components/containers/HomeCard/HomeCard.jsx
  client/src/components/containers/HomeCard/HomeCardProvisional.module.css
  client/src/redux/reducer/reducer.js
Labels: enhancement, fix

#38 Ruta trip/:id (FAKE)
  api/src/controllers/driver.json
  api/src/controllers/usersJson.js
  api/src/routes/trip.js
Labels: enhancement

#50 Añado lo necesario para Heroku y ElephantSQL
  api/index.js
  api/package.json
  api/src/db.js
Labels: fix

#48 Autenticacion y autorizacion
  api/src/controllers/authController.js
  api/src/controllers/usersController.js
  api/src/routes/auth.js
  api/src/routes/index.js
  client/src/App.js
  client/src/components/PrivateRoute/PrivateRoute.jsx
  client/src/components/containers/LoginForm/LoginForm.jsx
  client/src/components/containers/RegisterForm/RegisterForm.jsx
Labels: enhancement, fix

#58 Creacion de tabla Admin
  api/index.js
  api/src/Models/Admin.js
  api/src/Models/utils/Admin.js
  api/src/db.js
  api/src/routes/trip.js
  api/src/routes/userTest.js
  api/src/routes/users.js
Labels: enhancement, fix

#60 Rutas de Administrador para Banear & Desbanear usuarios
  api/src/Models/User.js
  api/src/Models/utils/Admin.js
  api/src/Models/utils/User.js
  api/src/controllers/adminController.js
  api/src/routes/admin.js
  api/src/routes/index.js
Labels: enhancement

#61 Back: Organizacion / Directorio api/src/config
  api/index.js
  api/src/app.js
  api/src/config/cors.js
  api/src/config/server.js
Labels: enhancement, organization

#69 Relaciones de viajes, usuarios y conductores.
  api/README.md
  api/src/Models/utils/Confirmer.js
  api/src/Models/utils/Creations.js
  api/src/Models/utils/Finders.js
  api/src/controllers/authController.js
  api/src/controllers/tripController.js
  api/src/database/relations.js
  api/src/routes/auth.js
  client/src/components/PrivateRoutes/PrivateRouteForLogged/PrivateRouteForLogged.jsx
Labels: enhancement, integration

#71 Reestructure toda la autenticacion, no funcionaba
  api/src/Models/utils/Finders.js
  api/src/config/cors.js
  api/src/controllers/Middlewares/middleware.js
  api/src/controllers/adminController.js
  api/src/controllers/authController.js
  api/src/routes/admin.js
  api/src/routes/auth.js
  client/src/App.js
  client/src/components/PrivateRoutes/PrivateRoute.jsx
  client/src/components/PrivateRoutes/PrivateRouteForLogged/PrivateRouteForLogged.jsx
  client/src/components/PrivateRoutes/PrivateRouteForNotAdmin/PrivateRouteForNotAdmin.jsx
  client/src/components/PrivateRoutes/PrivateRouteForNotLogged/PrivateRouteForNotLogged.jsx
Labels: enhancement, fix, integration

#76 Reorganizo las rutas y los distintos Homes
  client/src/App.js
  client/src/components/CardDetail/CardDetail.jsx
  client/src/components/Forms/Login/LoginForm/LoginForm.jsx
  client/src/components/Forms/LoginAdmin/LoginAdminForm/LoginAdminForm.jsx
  client/src/components/Forms/NewPassword/NewPasswordForm/NewPasswordForm.jsx
  client/src/components/Forms/RecoveryPassword/RecoveryPasswordForm/RecoveryPasswordForm.jsx
  client/src/components/Forms/Register/RegisterForm/RegisterForm.jsx
  client/src/components/Home/home.jsx
  client/src/components/Home/homeDrivers.jsx
  client/src/components/Home/homePassengers.jsx
  client/src/components/NavBar/navbar.js
  client/src/components/NavBar/navbarDrivers.jsx
  client/src/components/NavBar/navbarPassengers.jsx
  client/src/components/PrivateRoutes/PrivateRoute.jsx
Labels: fix

#78 Los filtros se apilan y cambie una validacion
  api/src/controllers/Middlewares/middleware.js
  api/src/controllers/authController.js
  client/src/components/Filters/filterByCapacity.jsx
  client/src/components/Filters/filterByDate.jsx
  client/src/components/Forms/Register/RegisterForm/RegisterForm.jsx
  client/src/components/Home/home.jsx
  client/src/hooks/validateField.js
  client/src/redux/actions/getFilteredTrips.js
  client/src/redux/reducer/reducer.js
Labels: enhancement, fix

#79 Almacenar datos falsos en al base de datos
  api/index.js
  api/src/Models/Car.js
  api/src/Models/Driver.js
  api/src/Models/Trip.js
  api/src/Models/utils/Creations.js
  api/src/Models/utils/Finders.js
  api/src/controllers/tripController.js
  api/src/database/data.json
  api/src/database/fake.js
  api/src/database/relations.js
  api/src/routes/trip.js
Labels: enhancement, fix, integration

#82 Arreglo registro y login de usuario de Google
  api/src/Models/utils/Confirmer.js
  api/src/controllers/authController.js
Labels: fix

#85 Feat code recovery
  api/README.md
  api/src/Models/User.js
  api/src/Models/utils/Admin.js
  api/src/Models/utils/Finders.js
  api/src/Models/utils/Recovery.js
  api/src/controllers/passwordController.js
  api/src/database/fake.js
  api/src/routes/pass.js
  client/src/components/Forms/RecoveryPassword/RecoveryPasswordForm/RecoveryPasswordForm.jsx
Labels: enhancement, integration

#92 Publicar viajes, hacerte conductor y agregar autos
  api/src/Models/Car.js
  api/src/Models/Trip.js
  api/src/Models/utils/Creations.js
  api/src/Models/utils/Finders.js
  api/src/config/cors.js
  api/src/controllers/CarController.js
  api/src/controllers/Middlewares/middleware.js
  api/src/controllers/authController.js
  api/src/controllers/passwordController.js
  api/src/controllers/tripController.js
  api/src/database/data.json
  api/src/database/fake.js
  api/src/routes/auth.js
  api/src/routes/car.js
  api/src/routes/index.js
  api/src/routes/pass.js
  api/src/routes/trip.js
  client/src/App.js
  client/src/components/CardDetail/CardDetail.jsx
  client/src/components/CardDetail/CardDetail.module.css
  client/src/components/Forms/AddCar/AddCar.jsx
  client/src/components/Forms/AddCar/AddCar.module.css
  client/src/components/Forms/NewPassword/NewPasswordForm/NewPasswordForm.jsx
  client/src/components/Forms/PublicTrip/PublicTrip.jsx
  client/src/components/Forms/RecoveryPassword/RecoveryPasswordForm/RecoveryPasswordForm.jsx
  client/src/components/Forms/UserToDriver/UserToDriver.jsx
  client/src/components/Home/home.jsx
  client/src/components/Home/homeDrivers.jsx
  client/src/components/Home/homePassengers.jsx
  client/src/components/Sections/HomeCard/HomeCard.jsx
  client/src/components/Terminos/Terminos.jsx
Labels: integration

#93 Nuevo hook para privatizar las rutas
  api/src/Models/utils/Confirmer.js
  api/src/controllers/Middlewares/middleware.js
  api/src/controllers/adminController.js
  api/src/controllers/authController.js
  api/src/controllers/passwordController.js
  client/src/App.js
  client/src/components/Home/home.jsx
  client/src/components/PrivateRoutes/PrivateRoute.jsx
  client/src/hooks/useAuthorized.js
Labels: enhancement, integration

#94 Admin Functions - Backend
  api/src/Models/Driver.js
  api/src/Models/User.js
  api/src/Models/utils/Admin.js
  api/src/controllers/adminController.js
  api/src/controllers/authController.js
  api/src/routes/auth.js
  client/src/App.js
  client/src/components/AdminPanel/AdminPanel.jsx
  client/src/components/PrivateRoutes/PrivateRoute.jsx
  client/src/components/Sections/User/User.jsx
  client/src/components/Sections/User/User.module.css
  client/src/hooks/useBan.js
Labels: enhancement, integration

#101 Admin Panel, Loader componente, Error component
  client/src/assets/Buttons/allow_permise.png
  client/src/assets/Buttons/banned_permise.png
  client/src/assets/Loader/car-error.png
  client/src/assets/NavBar/admin-logo.png
  client/src/components/AdminPanel/AdminPanel.jsx
  client/src/components/AdminPanel/AdminPanel.module.css
  client/src/components/PrivateRoutes/PrivateRoute.jsx
  client/src/components/Sections/Error/Error.jsx
  client/src/components/Sections/Error/Error.module.css
  client/src/components/Sections/User/User.jsx
  client/src/components/Sections/User/User.module.css
  client/src/hooks/useBan.js
Labels: enhancement

#102 Cositas varias
  api/src/Models/utils/Confirmer.js
  client/src/components/Sections/User/User.jsx
  client/src/hooks/validateField.js
Labels: fix

#116 Login Page responsive
  client/src/components/Forms/Login/Login.jsx
  client/src/components/Forms/Login/Login.module.css
  client/src/components/Forms/Login/LoginForm/LoginForm.jsx
  client/src/components/Forms/Login/LoginForm/LoginForm.module.css
  client/src/components/Sections/Button/Button.module.css
  client/src/components/Sections/InputField/InputField.module.css
Labels: fix, integration

#118 Switch React Router Eliminado
  client/src/App.js
  client/src/hooks/useAuthorized.js
Labels: bug, fix

#126 Subida imagen de perfil
  api/src/controllers/authController.js
  api/src/routes/auth.js
  client/src/assets/User/save-img.png
  client/src/components/Profile/ImageProfile/ImageProfile.jsx
  client/src/components/Profile/ImageProfile/ImageProfile.module.css
  client/src/components/Profile/Profile.jsx
  client/src/components/Profile/Profile.module.css
Labels: enhancement
